// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA55qKtM_rBI3aUQ1IEVes88DERDyaTR_0',
    appId: '1:87588663721:web:0863dded3d2138562e14b8',
    messagingSenderId: '87588663721',
    projectId: 'facefpalooza-8fed4',
    authDomain: 'facefpalooza-8fed4.firebaseapp.com',
    storageBucket: 'facefpalooza-8fed4.firebasestorage.app',
    measurementId: 'G-LWPQK1KV7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAanJ7JFABZ1iFeTitMXeN8QsJ5upeC0xw',
    appId: '1:87588663721:android:be5f6da31586855d2e14b8',
    messagingSenderId: '87588663721',
    projectId: 'facefpalooza-8fed4',
    storageBucket: 'facefpalooza-8fed4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv4l6-gM3zOlYEOSdHOR1EwW88LfH3rIY',
    appId: '1:87588663721:ios:e12e0039cec576fc2e14b8',
    messagingSenderId: '87588663721',
    projectId: 'facefpalooza-8fed4',
    storageBucket: 'facefpalooza-8fed4.firebasestorage.app',
    iosBundleId: 'com.example.facefpalooza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv4l6-gM3zOlYEOSdHOR1EwW88LfH3rIY',
    appId: '1:87588663721:ios:e12e0039cec576fc2e14b8',
    messagingSenderId: '87588663721',
    projectId: 'facefpalooza-8fed4',
    storageBucket: 'facefpalooza-8fed4.firebasestorage.app',
    iosBundleId: 'com.example.facefpalooza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA55qKtM_rBI3aUQ1IEVes88DERDyaTR_0',
    appId: '1:87588663721:web:88c7a8c3822b07f52e14b8',
    messagingSenderId: '87588663721',
    projectId: 'facefpalooza-8fed4',
    authDomain: 'facefpalooza-8fed4.firebaseapp.com',
    storageBucket: 'facefpalooza-8fed4.firebasestorage.app',
    measurementId: 'G-12W0G6YC3R',
  );
}
