// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOkbdzkcciP5kLsO_RKoBXB3sitYPpAAY',
    appId: '1:991709821352:web:d479f55cbb05d20330459d',
    messagingSenderId: '991709821352',
    projectId: 'facefpalooza-fc0f2',
    authDomain: 'facefpalooza-fc0f2.firebaseapp.com',
    storageBucket: 'facefpalooza-fc0f2.appspot.com',
    measurementId: 'G-0LH1PY89KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU9Qz7dsRpqpyhv7tfcOSfMKD7DhhWEVM',
    appId: '1:991709821352:android:9065e62b63d3eef930459d',
    messagingSenderId: '991709821352',
    projectId: 'facefpalooza-fc0f2',
    storageBucket: 'facefpalooza-fc0f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhOBlEoJSjiJ918smqCCN9Whc-INZPNZw',
    appId: '1:991709821352:ios:a6c7bf200f4a832c30459d',
    messagingSenderId: '991709821352',
    projectId: 'facefpalooza-fc0f2',
    storageBucket: 'facefpalooza-fc0f2.appspot.com',
    iosBundleId: 'com.example.facefpalooza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhOBlEoJSjiJ918smqCCN9Whc-INZPNZw',
    appId: '1:991709821352:ios:a6c7bf200f4a832c30459d',
    messagingSenderId: '991709821352',
    projectId: 'facefpalooza-fc0f2',
    storageBucket: 'facefpalooza-fc0f2.appspot.com',
    iosBundleId: 'com.example.facefpalooza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOkbdzkcciP5kLsO_RKoBXB3sitYPpAAY',
    appId: '1:991709821352:web:e14d3ec711c89b1130459d',
    messagingSenderId: '991709821352',
    projectId: 'facefpalooza-fc0f2',
    authDomain: 'facefpalooza-fc0f2.firebaseapp.com',
    storageBucket: 'facefpalooza-fc0f2.appspot.com',
    measurementId: 'G-8GJRC0SCDV',
  );

}