// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgKJ7K1WM_4zzqrVMgICVHE4FrcI-H0Lo',
    appId: '1:330320923746:web:82312f6ecc4e78f80a553b',
    messagingSenderId: '330320923746',
    projectId: 'facefpalooza-48b66',
    authDomain: 'facefpalooza-48b66.firebaseapp.com',
    storageBucket: 'facefpalooza-48b66.firebasestorage.app',
    measurementId: 'G-8VNJKBWTM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA3zBN3zm4f4oW1UFDOwcsszWmK2dNo08',
    appId: '1:330320923746:android:5ba119dd97297e6c0a553b',
    messagingSenderId: '330320923746',
    projectId: 'facefpalooza-48b66',
    storageBucket: 'facefpalooza-48b66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgyrhV-diOWFifLoPQExIz-WeLwxoFuzk',
    appId: '1:330320923746:ios:c3537d60c930f7910a553b',
    messagingSenderId: '330320923746',
    projectId: 'facefpalooza-48b66',
    storageBucket: 'facefpalooza-48b66.firebasestorage.app',
    iosBundleId: 'com.example.facefpalooza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgyrhV-diOWFifLoPQExIz-WeLwxoFuzk',
    appId: '1:330320923746:ios:c3537d60c930f7910a553b',
    messagingSenderId: '330320923746',
    projectId: 'facefpalooza-48b66',
    storageBucket: 'facefpalooza-48b66.firebasestorage.app',
    iosBundleId: 'com.example.facefpalooza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgKJ7K1WM_4zzqrVMgICVHE4FrcI-H0Lo',
    appId: '1:330320923746:web:55248779f0eaf68d0a553b',
    messagingSenderId: '330320923746',
    projectId: 'facefpalooza-48b66',
    authDomain: 'facefpalooza-48b66.firebaseapp.com',
    storageBucket: 'facefpalooza-48b66.firebasestorage.app',
    measurementId: 'G-JX0J9XJYZR',
  );

}