name: facefpalooza
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.0  # ou a versão mais recente disponível

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
